services:
  - type: web
    name: soil-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account.json
    secrets:
      - source: service_account_json
        target: /etc/secrets/service_account.json
