services:
  - type: web
    name: soil-analyzer
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.10.13
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service_account
    secretFiles:
      - name: service_account
        path: /etc/secrets/service_account
